import { Col, Container, Row, Badge, Tabs, Tab } from "react-bootstrap";
import NavBar from '../components/navbar';
import Head from 'next/head';
import FooterSection from '../components/footer';

export default function CampSite(params) {
    return (
        <div>
            <Head>
                <title>Pawna Camping</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <main>
                <div className="headBanner py-5">
                    <Container className="pt-5 pb-3">
                        <Row >
                            <Col>
                                <Badge bg="light" text="dark" className="mb-2">Pawna Camp</Badge>
                                <h1 className="fw-bold fs-1">Pawna Camping</h1>
                                <p className="fs-4">Pawna Camping is the best camping site near Lonavala.</p>
                                <span>
                                    {Array.from({ length: 5 }).map((_, idx) => (
                                        <svg key={idx} xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#ffc107" className="bi bi-star-fill" viewBox="0 0 16 16">
                                            <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                                        </svg>
                                    ))}
                                </span>
                            </Col>
                        </Row>
                    </Container>
                </div>
                <Container className="py-5">
                    <Row>
                        <Col>
                            <Tabs
                                defaultActiveKey="home"
                                transition={false}
                                id="noanim-tab-example"
                                className="mb-3"
                            >
                                <Tab eventKey="about" title="About">
                                    <h4>About</h4>
                                    <p>Pawna Camps are complete heaven on earth place where there is a 100% chance
                                        of overdose of happiness and satisfaction. The waylaid to this beautiful
                                        location from the major city like Pune is about 68 km from your affordable
                                        transport, 20 km far away from Kamshet, and 38 km from Lonavala. You can book
                                        Pawna hill tents at ₹ 500/per person. The remaining payment you can pay at the
                                        campsite.
                                        <br /> <br />
                                        A 2 days 1-night camping on the banks of the beautiful Pawna Lake is here. Take part in this adventure to escape from the hassles of your city life.
                                        The lake is one of the popular artificial lakes located 10 kilometers away from Kamshet on the old Mumbai- Pune highway.
                                        It has become an important campsite after the construction of the Pawna Dam.
                                        This package comes with camping, sightseeing around the lake, a bonfire with music, barbeque dinner, star gazing, adventure activities, etc.
                                        There are different packages you can choose from like Games + Camping, Camping + Gaming+ Camping + Games, Camping + Trekking, and so on.
                                        Kayaking will be on two-seater kayaks.
                                        <br /> <br />
                                        The check-in time is 04:00 PM and the check-out time is 11:00 AM on the second day of the camping.</p>
                                </Tab>
                                <Tab eventKey="location" title="Location">
                                    <h4>Location</h4>
                                    <iframe style={{ "border": "0" }} width="1000" height="400"
                                        allowFullScreen="allowfullscreen"
                                        data-src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3779.436369339593!2d73.47613041489531!3d18.689271887310998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x802e1ac93045b42d!2sPawna%20Camping!5e0!3m2!1sen!2sin!4v1637398319779!5m2!1sen!2sin"
                                        className=" lazyloaded" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="></iframe>
                                </Tab>
                                <Tab eventKey="campingSchedule" title="Camping Schedule">
                                    <h4>Camping Schedule</h4><br />
                                    <h5>Day 1 – Arrival at the Campsite</h5>
                                    <ol>
                                        <li>Arrive at the campsite by around and check-in by 04:00 PM. Walk around the vicinity and explore the location on your own.</li>
                                        <li>Once you are settled down, tea and snacks will be served at around 05:30 PM.</li>
                                        <li>Enjoy soothing music and a lively bonfire at the campsite that would be ready by 07:00 PM.</li>
                                        <li>The barbeque session will start by 07:30 PM. Try your hands at it and enjoy the fun moments.</li>
                                        <li>By 09:00 PM, dinner will be ready. If you feel like spending more time gazing at the sky and its stars, all the time and space will be yours.</li>
                                    </ol>
                                    <br />
                                    <h5>Day 2 – Check-out from the Campsite</h5>
                                    <ol>
                                        <li>Once the breakfast is served around 09:00 AM, you are free to indulge in the adventure activities or the short trek as you wish.</li>
                                        <li>Post the activities, you can check-out from the camps by 11:00 AM.</li>
                                    </ol>
                                </Tab>
                                <Tab eventKey="meal" title="Meal">
                                    <h4>Meal</h4><br />
                                    <ul>
                                        <li>Snacks in the evening: Tea and Pakoda (More options will be provided on Campsite)</li>
                                        <li>Veg- BBQ: marinated Paneer and assorted vegetables</li>
                                        <li>Non Veg- BBQ: marinated chicken with assorted vegetables</li>
                                        <li>Veg- Dinner: Dal tadka, Paneer sabji or veg sabji, chapati, steamed rice, salad.</li>
                                        <li>Non Veg- Dinner: Chicken curry, Chicken dry masala, chapati, steamed rice, salad.</li>
                                        <li>Breakfast on the second day: Tea and Poha (More options will be provided after the payment)</li>
                                        <li>Mineral water during the stay (2L).</li>
                                    </ul>
                                </Tab>
                                <Tab eventKey="thingsToCarry" title="Things To Carry">
                                    <h4>Things To Carry</h4><br />
                                    <ul>
                                        <li>Torch</li>
                                        <li>Personal medicines</li>
                                        <li>Extra pair of clothes, Slippers</li>
                                        <li>Comfortable footwear</li>
                                        <li>Warm clothing or extra blanket(during winters)</li>
                                        <li>Umbrella (during monsoon)</li>
                                    </ul>
                                </Tab>
                                <Tab eventKey="faq" title="FAQ">
                                    <h4>FAQ</h4><br />
                                </Tab>
                            </Tabs>
                        </Col>
                    </Row>
                </Container>
            </main>
            <FooterSection />
        </div>

    )
}